
(** 
    https://www.organdonor.gov/awareness/organizations/local-opo.html
 *)
module OPO = struct 

    type t =
    | ALCH_TX1
    | ALUA_TX1
    | ALVA_TX1
    | ARBH_TX1
    | ARCH_TX1
    | ARUA_TX1
    | AZCH_TX1
    | AZGS_TX1
    | AZMC_TX1
    | AZSJ_TX1
    | AZUA_TX1
    | CACH_TX1
    | CACL_TX1
    | CACS_TX1
    | CAGH_TX1
    | CAIM_TX1
    | CALA_TX1
    | CALL_TX1
    | CAMB_TX1
    | CAPC_TX1
    | CAPM_TX1
    | CASD_TX1
    | CASF_TX1
    | CASG_TX1
    | CASH_TX1
    | CASJ_TX1
    | CASM_TX1
    | CASU_TX1
    | CASV_TX1
    | CAUC_TX1
    | CAUH_TX1
    | COCH_TX1
    | COSL_TX1
    | COUC_TX1
    | CTHH_TX1
    | CTYN_TX1
    | DCCH_TX1
    | DCGU_TX1
    | DCGW_TX1
    | DCWH_TX1
    | DCWR_TX1
    | DEAI_TX1
    | DECC_TX1
    | FLBC_TX1
    | FLCC_TX1
    | FLFH_TX1
    | FLHM_TX1
    | FLJM_TX1
    | FLLM_TX1
    | FLMR_TX1
    | FLSH_TX1
    | FLSL_TX1
    | FLTG_TX1
    | FLUF_TX1
    | GAEH_TX1
    | GAEM_TX1
    | GAMC_TX1
    | GAPH_TX1
    | HIQM_TX1
    | IAIM_TX1
    | IAIV_TX1
    | IAMH_TX1
    | IAVA_TX1
    | ILCH_TX1
    | ILCM_TX1
    | ILLU_TX1
    | ILMM_TX1
    | ILNM_TX1
    | ILPL_TX1
    | ILSF_TX1
    | ILUC_TX1
    | ILUI_TX1
    | INIM_TX1
    | INLH_TX1
    | INSV_TX1
    | KSUK_TX1
    | KYJH_TX1
    | KYKC_TX1
    | KYUK_TX1
    | LACH_TX1
    | LAOF_TX1
    | LATU_TX1
    | LAWK_TX1
    | MABI_TX1
    | MABS_TX1
    | MABU_TX1
    | MACH_TX1
    | MALC_TX1
    | MAMG_TX1
    | MANM_TX1
    | MAPB_TX1
    | MAUM_TX1
    | MDJH_TX1
    | MDUM_TX1
    | MEMC_TX1
    | MIBH_TX1
    | MICH_TX1
    | MIDV_TX1
    | MIHF_TX1
    | MIHH_TX1
    | MISH_TX1
    | MISJ_TX1
    | MISM_TX1
    | MIUM_TX1
    | MNAN_TX1
    | MNCM_TX1
    | MNHC_TX1
    | MNMC_TX1
    | MNUM_TX1
    | MOBH_TX1
    | MOCG_TX1
    | MOCH_TX1
    | MOCM_TX1
    | MOLH_TX1
    | MORH_TX1
    | MOSL_TX1
    | MOUM_TX1
    | MSUM_TX1
    | NCBG_TX1
    | NCCM_TX1
    | NCDU_TX1
    | NCEC_TX1
    | NCMH_TX1
    | NDMC_TX1
    | NDSL_TX1
    | NEUN_TX1
    | NHDH_TX1
    | NJBI_TX1
    | NJHK_TX1
    | NJLL_TX1
    | NJRW_TX1
    | NJSB_TX1
    | NJUH_TX1
    | NMAQ_TX1
    | NMPH_TX1
    | NVUM_TX1
    | NYAM_TX1
    | NYCC_TX1
    | NYCP_TX1
    | NYDS_TX1
    | NYEC_TX1
    | NYFL_TX1
    | NYMA_TX1
    | NYMS_TX1
    | NYNS_TX1
    | NYNY_TX1
    | NYSB_TX1
    | NYUC_TX1
    | NYUM_TX1
    | NYWC_TX1
    | OHCC_TX1
    | OHCH_TX1
    | OHCM_TX1
    | OHCO_TX1
    | OHOU_TX1
    | OHTC_TX1
    | OHUC_TX1
    | OHUH_TX1
    | OKBC_TX1
    | OKMD_TX1
    | OKSF_TX1
    | OKSJ_TX1
    | ORGS_TX1
    | ORUO_TX1
    | ORVA_TX1
    | PAAE_TX1
    | PAAG_TX1
    | PACC_TX1
    | PACH_TX1
    | PACP_TX1
    | PAGM_TX1
    | PAHE_TX1
    | PAHH_TX1
    | PAHM_TX1
    | PALH_TX1
    | PALV_TX1
    | PAPH_TX1
    | PAPT_TX1
    | PASC_TX1
    | PATJ_TX1
    | PATU_TX1
    | PAUP_TX1
    | PAVA_TX1
    | PRCC_TX1
    | PRSJ_TX1
    | RIRH_TX1
    | SCMU_TX1
    | SDMK_TX1
    | SDSV_TX1
    | TNBM_TX1
    | TNEM_TX1
    | TNLB_TX1
    | TNMH_TX1
    | TNPV_TX1
    | TNST_TX1
    | TNUK_TX1
    | TNVA_TX1
    | TNVU_TX1
    | TXAS_TX1
    | TXBC_TX1
    | TXCF_TX1
    | TXCM_TX1
    | TXCT_TX1
    | TXDC_TX1
    | TXDM_TX1
    | TXDR_TX1
    | TXFW_TX1
    | TXHD_TX1
    | TXHH_TX1
    | TXHI_TX1
    | TXHS_TX1
    | TXJS_TX1
    | TXLP_TX1
    | TXMC_TX1
    | TXMH_TX1
    | TXPL_TX1
    | TXPM_TX1
    | TXSP_TX1
    | TXSW_TX1
    | TXTC_TX1
    | TXTX_TX1
    | TXUC_TX1
    | TXVA_TX1
    | UTLD_TX1
    | UTMC_TX1
    | UTPC_TX1
    | VACH_TX1
    | VAFH_TX1
    | VAHD_TX1
    | VAMC_TX1
    | VANG_TX1
    | VAUV_TX1
    | VTMC_TX1
    | WACH_TX1
    | WASH_TX1
    | WASM_TX1
    | WAUW_TX1
    | WAVM_TX1
    | WICH_TX1
    | WISE_TX1
    | WISL_TX1
    | WIUW_TX1
    | WVCA_TX1
    
end
